<a href="https://colab.research.google.com/github/swarnaparasuraman/DSI/blob/main/Task_1_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
arr=np.array(42)
b=np.array([1,2,3])
c=np.array([[[1,2,3],[4,5,6]],[[3,2,1],[4,5,7]]])
print(c.ndim)

3


In [ ]:

import numpy as np
c=np.array([[[1,2,3],[4,5,6]],[[3,2,1],[4,5,7]]])
print(c[1,1])
a=np.array([[1,2,3],[4,5,6],[3,2,1],[4,5,7]])
print(a[1,1])

[4 5 7]
5


In [ ]:

import numpy as np
a=np.array([1,2,3])
print(a[2])

3


In [ ]:

import numpy as np
b=np.array([1,2,3,4,5,6])
print(b[1:5])

[2 3 4 5]


In [ ]:

# Python program to demonstrate
# indexing in numpy array
import numpy as np

# Initial Array
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])
print("Initial Array: ")
print(arr)

# Printing a range of Array
# with the use of slicing method
sliced_arr = arr[:2, ::2]
print ("Array with first 2 rows and"
    " alternate columns(0 and 2):\n", sliced_arr)

# Printing elements at
# specific Indices
Index_arr = arr[[1, 1, 0, 3],
                [3, 2, 1, 0]]
print ("\nElements at indices (1, 3), "
    "(1, 2), (0, 1), (3, 0):\n", Index_arr)

Initial Array: 
[[-1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]
 [ 2.6  0.   7.   8. ]
 [ 3.  -7.   4.   2. ]]
Array with first 2 rows and alternate columns(0 and 2):
 [[-1.  0.]
 [ 4.  6.]]

Elements at indices (1, 3), (1, 2), (0, 1), (3, 0):
 [0. 6. 2. 3.]


In [ ]:

# Python program to demonstrate
# basic operations on single array
import numpy as np

# Defining Array 1
a = np.array([[1, 2],
              [3, 4]])

# Defining Array 2
b = np.array([[4, 3],
              [2, 1]])

# Adding 1 to every element
print ("Adding 1 to every element:", a + 1)

# Subtracting 2 from each element
print ("\nSubtracting 2 from each element:", b - 2)

# sum of array elements
# Performing Unary operations
print ("\nSum of all array "
       "elements: ", a.sum())

# Adding two arrays
# Performing Binary operations
print ("\nArray sum:\n", a + b)

Adding 1 to every element: [[2 3]
 [4 5]]

Subtracting 2 from each element: [[ 2  1]
 [ 0 -1]]

Sum of all array elements:  10

Array sum:
 [[5 5]
 [5 5]]


In [ ]:

# Python Program to create
# a data type object
import numpy as np

# Integer datatype
# guessed by Numpy
x = np.array([1, 2])
print("Integer Datatype: ")
print(x.dtype)

# Float datatype
# guessed by Numpy
x = np.array([1.0, 2.0])
print("\nFloat Datatype: ")
print(x.dtype)

# Forced Datatype
x = np.array([1, 2], dtype = np.int64)
print("\nForcing a Datatype: ")
print(x.dtype)

Integer Datatype: 
int64

Float Datatype: 
float64

Forcing a Datatype: 
int64


In [ ]:

import numpy as np

# First Array
arr1 = np.array([[4, 7], [2, 6]],
                 dtype = np.float64)

# Second Array
arr2 = np.array([[3, 6], [2, 8]],
                 dtype = np.float64)

# Addition of two Arrays
Sum = np.add(arr1, arr2)
print("Addition of Two Arrays: ")
print(Sum)

# Addition of all Array elements
# using predefined sum method
Sum1 = np.sum(arr1)
print("\nAddition of Array elements: ")
print(Sum1)

# Square root of Array
Sqrt = np.sqrt(arr1)
print("\nSquare root of Array1 elements: ")
print(Sqrt)

# Transpose of Array
# using In-built function 'T'
Trans_arr = arr1.T
print("\nTranspose of Array: ")
print(Trans_arr)

Addition of Two Arrays: 
[[ 7. 13.]
 [ 4. 14.]]

Addition of Array elements: 
19.0

Square root of Array1 elements: 
[[2.         2.64575131]
 [1.41421356 2.44948974]]

Transpose of Array: 
[[4. 2.]
 [7. 6.]]


In [ ]:

import numpy as geek
in_num1 = 10
in_num2 = 11

print ("Input  number1 : ", in_num1)
print ("Input  number2 : ", in_num2)

out_num = geek.bitwise_and(in_num1, in_num2)
print ("bitwise_and of 10 and 11 : ", out_num)

Input  number1 :  10
Input  number2 :  11
bitwise_and of 10 and 11 :  10


In [ ]:
import numpy as geek

in_arr1 = [2, 8, 125]
in_arr2 = [3, 3, 115]

print ("Input array1 : ", in_arr1)
print ("Input array2 : ", in_arr2)

out_arr = geek.bitwise_and(in_arr1, in_arr2)
print ("Output array after bitwise_and: ", out_arr)

Input array1 :  [2, 8, 125]
Input array2 :  [3, 3, 115]
Output array after bitwise_and:  [  2   0 113]


In [ ]:
# Python program explaining
# invert() function

import numpy as geek
in_num = 10
print ("Input  number : ", in_num)

out_num = geek.invert(in_num)
print ("inversion of 10 : ", out_num)

Input  number :  10
inversion of 10 :  -11


In [ ]:
import numpy as np

arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]
